// Resource configuration for the generic admin CRUD manager.
// type: text | textarea | number | switch | select | image | tags

const GALLERY_CATS = ["Arrival", "Observation", "Education", "Religious Activities", "Social Activities", "Environment", "Digitalization", "Community Development", "Evaluation", "Closing"];

export const RESOURCES = [
  {
    path: "team",
    label: "Team Members",
    singular: "Team Member",
    icon: "Users",
    columns: ["name", "role", "studyProgram"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "nim", label: "Student ID (NIM)", type: "text" },
      { name: "studyProgram", label: "Study Program", type: "text" },
      { name: "role", label: "Role", type: "text" },
      { name: "photo", label: "Profile Photo", type: "image" },
      { name: "bio", label: "Bio", type: "textarea" },
      { name: "instagram", label: "Instagram URL", type: "text" },
      { name: "whatsapp", label: "WhatsApp Number", type: "text" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "isActive", label: "Active", type: "switch", default: true },
    ],
  },
  {
    path: "programs",
    label: "Programs",
    singular: "Program",
    icon: "LayoutGrid",
    columns: ["number", "title", "icon"],
    fields: [
      { name: "number", label: "Number", type: "number" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "icon", label: "Lucide Icon Name", type: "text" },
      { name: "activities", label: "Activities", type: "tags" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "isActive", label: "Active", type: "switch", default: true },
    ],
  },
  {
    path: "gallery",
    label: "Gallery",
    singular: "Gallery Item",
    icon: "Images",
    columns: ["title", "category"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "imageUrl", label: "Image", type: "image" },
      { name: "category", label: "Category", type: "select", options: GALLERY_CATS },
      { name: "caption", label: "Caption", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "location", label: "Location", type: "text" },
      { name: "date", label: "Date", type: "text" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "isPublished", label: "Published", type: "switch", default: true },
    ],
  },
  {
    path: "news",
    label: "News",
    singular: "Article",
    icon: "Newspaper",
    columns: ["title", "category"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug (URL)", type: "text" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "content", label: "Content", type: "textarea", rows: 8 },
      { name: "coverImage", label: "Cover Image", type: "image" },
      { name: "category", label: "Category", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "author", label: "Author", type: "text" },
      { name: "publishedAt", label: "Published Date", type: "text" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "isPublished", label: "Published", type: "switch", default: true },
    ],
  },
  {
    path: "timeline",
    label: "Timeline",
    singular: "Timeline Stage",
    icon: "GitCommitVertical",
    columns: ["number", "title"],
    fields: [
      { name: "number", label: "Number (e.g. 01)", type: "text" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "date", label: "Date", type: "text" },
      { name: "image", label: "Image", type: "image" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "isActive", label: "Active", type: "switch", default: true },
    ],
  },
  {
    path: "archives",
    label: "Archives",
    singular: "Archive",
    icon: "Archive",
    columns: ["title", "type"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "type", label: "Type", type: "select", options: ["document", "schedule", "video", "image"] },
      { name: "url", label: "Link URL", type: "text" },
      { name: "embedUrl", label: "Embed URL", type: "text" },
      { name: "icon", label: "Lucide Icon Name", type: "text" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "isActive", label: "Active", type: "switch", default: true },
    ],
  },
  {
    path: "videos",
    label: "Videos",
    singular: "Video",
    icon: "Video",
    columns: ["title", "category"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "thumbnail", label: "Thumbnail", type: "image" },
      { name: "videoUrl", label: "Video URL (YouTube / Drive)", type: "text" },
      { name: "type", label: "Type", type: "select", options: ["youtube", "drive", "direct"] },
      { name: "category", label: "Category", type: "text" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "isPublished", label: "Published", type: "switch", default: true },
    ],
  },
  {
    path: "memories",
    label: "Memories",
    singular: "Memory",
    icon: "Heart",
    columns: ["title", "category"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "imageUrl", label: "Image", type: "image" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "isActive", label: "Active", type: "switch", default: true },
    ],
  },
  {
    path: "location",
    label: "Location",
    singular: "Location",
    icon: "MapPin",
    columns: ["village", "regency"],
    fields: [
      { name: "village", label: "Village", type: "text", required: true },
      { name: "district", label: "District / Subdistrict", type: "text" },
      { name: "regency", label: "Regency", type: "text" },
      { name: "province", label: "Province", type: "text" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "latitude", label: "Latitude", type: "text" },
      { name: "longitude", label: "Longitude", type: "text" },
      { name: "googleMapsUrl", label: "Google Maps URL", type: "text" },
      { name: "embedUrl", label: "Map Embed URL", type: "textarea" },
      { name: "order", label: "Display Order", type: "number" },
      { name: "isActive", label: "Active", type: "switch", default: true },
    ],
  },
];
