// Konfigurasi resource untuk pengelola CRUD admin generik.
// type: text | textarea | number | switch | select | image | tags

const GALLERY_CATS = ["Kedatangan", "Observasi", "Pendidikan", "Keagamaan", "Kegiatan Sosial", "Lingkungan", "Digitalisasi", "Pemberdayaan Masyarakat", "Evaluasi", "Penutupan"];

export const RESOURCES = [
  {
    path: "team",
    label: "Anggota Tim",
    singular: "Anggota Tim",
    icon: "Users",
    columns: ["name", "role", "studyProgram"],
    reorderable: true,
    fields: [
      { name: "name", label: "Nama", type: "text", required: true },
      { name: "nim", label: "NIM", type: "text" },
      { name: "studyProgram", label: "Program Studi", type: "text" },
      { name: "role", label: "Jabatan", type: "text" },
      { name: "photo", label: "Foto Profil", type: "image" },
      { name: "bio", label: "Biografi", type: "textarea" },
      { name: "instagram", label: "URL Instagram", type: "text" },
      { name: "whatsapp", label: "Nomor WhatsApp", type: "text" },
      { name: "order", label: "Urutan Tampilan", type: "number" },
      { name: "isActive", label: "Aktif", type: "switch", default: true },
    ],
  },
  {
    path: "programs",
    label: "Program",
    singular: "Program",
    icon: "LayoutGrid",
    columns: ["number", "title", "icon"],
    fields: [
      { name: "number", label: "Nomor", type: "number" },
      { name: "title", label: "Judul", type: "text", required: true },
      { name: "description", label: "Deskripsi", type: "textarea" },
      { name: "icon", label: "Nama Ikon (Lucide)", type: "text" },
      { name: "activities", label: "Aktivitas", type: "tags" },
      { name: "order", label: "Urutan Tampilan", type: "number" },
      { name: "isActive", label: "Aktif", type: "switch", default: true },
    ],
  },
  {
    path: "gallery",
    label: "Galeri",
    singular: "Item Galeri",
    icon: "Images",
    columns: ["title", "category"],
    bulkImage: "imageUrl",
    reorderable: true,
    fields: [
      { name: "title", label: "Judul", type: "text", required: true },
      { name: "imageUrl", label: "Gambar", type: "image" },
      { name: "category", label: "Kategori", type: "select", options: GALLERY_CATS },
      { name: "caption", label: "Keterangan", type: "text" },
      { name: "description", label: "Deskripsi", type: "textarea" },
      { name: "location", label: "Lokasi", type: "text" },
      { name: "date", label: "Tanggal", type: "text" },
      { name: "order", label: "Urutan Tampilan", type: "number" },
      { name: "isPublished", label: "Dipublikasikan", type: "switch", default: true },
    ],
  },
  {
    path: "news",
    label: "Berita",
    singular: "Artikel",
    icon: "Newspaper",
    columns: ["title", "category"],
    fields: [
      { name: "title", label: "Judul", type: "text", required: true },
      { name: "slug", label: "Slug (URL)", type: "text" },
      { name: "excerpt", label: "Ringkasan", type: "textarea" },
      { name: "content", label: "Isi", type: "textarea", rows: 8 },
      { name: "coverImage", label: "Gambar Sampul", type: "image" },
      { name: "category", label: "Kategori", type: "text" },
      { name: "location", label: "Lokasi", type: "text" },
      { name: "author", label: "Penulis", type: "text" },
      { name: "publishedAt", label: "Tanggal Terbit", type: "text" },
      { name: "order", label: "Urutan Tampilan", type: "number" },
      { name: "isPublished", label: "Dipublikasikan", type: "switch", default: true },
    ],
  },
  {
    path: "timeline",
    label: "Perjalanan",
    singular: "Tahapan Perjalanan",
    icon: "GitCommitVertical",
    columns: ["number", "title"],
    fields: [
      { name: "number", label: "Nomor (mis. 01)", type: "text" },
      { name: "title", label: "Judul", type: "text", required: true },
      { name: "description", label: "Deskripsi", type: "textarea" },
      { name: "date", label: "Tanggal", type: "text" },
      { name: "image", label: "Gambar", type: "image" },
      { name: "order", label: "Urutan Tampilan", type: "number" },
      { name: "isActive", label: "Aktif", type: "switch", default: true },
    ],
  },
  {
    path: "archives",
    label: "Arsip",
    singular: "Arsip",
    icon: "Archive",
    columns: ["title", "type"],
    fields: [
      { name: "title", label: "Judul", type: "text", required: true },
      { name: "description", label: "Deskripsi", type: "textarea" },
      { name: "type", label: "Tipe", type: "select", options: ["document", "schedule", "video", "image"] },
      { name: "url", label: "URL Tautan", type: "text" },
      { name: "embedUrl", label: "URL Sematan", type: "text" },
      { name: "icon", label: "Nama Ikon (Lucide)", type: "text" },
      { name: "order", label: "Urutan Tampilan", type: "number" },
      { name: "isActive", label: "Aktif", type: "switch", default: true },
    ],
  },
  {
    path: "videos",
    label: "Video",
    singular: "Video",
    icon: "Video",
    columns: ["title", "category"],
    fields: [
      { name: "title", label: "Judul", type: "text", required: true },
      { name: "description", label: "Deskripsi", type: "textarea" },
      { name: "thumbnail", label: "Thumbnail", type: "image" },
      { name: "videoUrl", label: "URL Video (YouTube / Drive)", type: "text" },
      { name: "type", label: "Tipe", type: "select", options: ["youtube", "drive", "direct"] },
      { name: "category", label: "Kategori", type: "text" },
      { name: "order", label: "Urutan Tampilan", type: "number" },
      { name: "isPublished", label: "Dipublikasikan", type: "switch", default: true },
    ],
  },
  {
    path: "memories",
    label: "Kenangan",
    singular: "Kenangan",
    icon: "Heart",
    columns: ["title", "category"],
    bulkImage: "imageUrl",
    reorderable: true,
    fields: [
      { name: "title", label: "Judul", type: "text", required: true },
      { name: "category", label: "Kategori", type: "text" },
      { name: "description", label: "Deskripsi", type: "textarea" },
      { name: "imageUrl", label: "Gambar", type: "image" },
      { name: "order", label: "Urutan Tampilan", type: "number" },
      { name: "isActive", label: "Aktif", type: "switch", default: true },
    ],
  },
  {
    path: "location",
    label: "Lokasi",
    singular: "Lokasi",
    icon: "MapPin",
    columns: ["village", "regency"],
    fields: [
      { name: "village", label: "Desa", type: "text", required: true },
      { name: "district", label: "Kecamatan", type: "text" },
      { name: "regency", label: "Kabupaten", type: "text" },
      { name: "province", label: "Provinsi", type: "text" },
      { name: "address", label: "Alamat", type: "textarea" },
      { name: "latitude", label: "Lintang (Latitude)", type: "text" },
      { name: "longitude", label: "Bujur (Longitude)", type: "text" },
      { name: "googleMapsUrl", label: "URL Google Maps", type: "text" },
      { name: "embedUrl", label: "URL Sematan Peta", type: "textarea" },
      { name: "order", label: "Urutan Tampilan", type: "number" },
      { name: "isActive", label: "Aktif", type: "switch", default: true },
    ],
  },
];
